python train.py \
    --seed 7777777 \
    --model_name_or_path google/mt5-small \
    --do_train=True \
    --output_dir ./cache/test \
    --num_train_epochs 30 \
    --per_device_train_batch_size=1 \
    --per_device_eval_batch_size=1 \
    --max_source_length=128 \
    --max_target_length=32 \
    --gradient_accumulation_steps 8 \
    --fp16=True \
    --report_to="wandb" \
    --do_eval=True\
    --train_file ./cache/train.jsonl \
    --eval_file ./cache/eval.jsonl \